### ISSUE TITLE
对 LDO 及其替代品的疑虑

### ISSUE THREAD

**Issue by ksumit12** [txp666/ElectronBot_Study#1]
因为原始存储库使用 lp2992 LDO。所以要用 XC6210B332MR 替换它，是否需要更改周围的电容器??
![lp2992](https://user-images.githubusercontent.com/70723407/203721780-2fbd2d83-7c2e-4d40-b165-6cb2515f101a.jpg)
![xcr](https://user-images.githubusercontent.com/70723407/203721814-7b4ae695-5698-4e96-8b6b-83f517510463.jpg)

顺便说一句，感谢您提供详细的 BOM。你有所有零件的制造商零件号吗???

**Comment by txp666** [comment]
不需要改，而且可以少焊一个10nf的电容，不过焊上也不影响，没有零件号 随便买的
